# Generated by Django 2.1.7 on 2020-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200106_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=None),
        ),
    ]
